  # Please make sure that your branch doesn't have '_' in the name.
  # This pipeline is tightly coupled with kubernetes namespace and Kubernetes dns, 
  # and a DNS-1123 label must consist of lower case alphanumeric characters or '-', 
  # and must start and end with an alphanumeric character.
  stages:
    - dev-build
    - prod-build
    - deploy

  variables:
    # K8s Namespaces Naming. 
    KUBE_NAMESPACE: $CI_COMMIT_BRANCH
    RELEASE_NAME: mautic
    # various stages, currently disabled, remove the variable to enable those steps
    # DEPLOY_DISABLED: "false"
    BUILD_DISABLED: "false"
    PROD_BUILD_DISABLED: "true"
    # PROD_RELEASE_DISABLED: "true"

  dev-build:
    image: docker:latest

    stage: dev-build
    variables:
      MAUTIC_REPOSITORY_URL: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic
      NGINX_REPOSITORY_URL: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic-nginx
    services:
    - docker:dind

    before_script:
      - apk add --no-cache curl jq python py-pip
      - pip install awscli

    script:
      - docker build -t $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA .
      - $(aws ecr get-login --no-include-email --region us-west-1)
      - docker push $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA
      - docker build -f Dockerfile-nginx -t $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA  .
      - docker push $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA

    only:
      refs:
        - branches
    except:
      refs:
        - master
      variables:
        - $BUILD_DISABLED    

  prod-build:
    image: docker:latest
    stage: prod-build
    variables:
      MAUTIC_REPOSITORY_URL: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic
      NGINX_REPOSITORY_URL: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic-nginx

    services:
    - docker:dind

    before_script:
      - apk add --no-cache curl jq python py-pip
      - pip install awscli

    script:
      - docker build -t $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA .
      - docker tag $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA $MAUTIC_REPOSITORY_URL:latest
      - $(aws ecr get-login --no-include-email --region us-west-1)
      - docker push $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA
      - docker push $MAUTIC_REPOSITORY_URL:latest
      - docker build -f Dockerfile-nginx -t $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA  .
      - docker tag $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA $NGINX_REPOSITORY_URL:latest
      - docker push $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA
      - docker push $NGINX_REPOSITORY_URL:latest
    
    only:
      - master
    except:
      variables:
        - $PROD_BUILD_DISABLED

  deploy:
    stage: deploy
    image: akashkaveti/base_image:latest
    
    before_script:
      - kubectl describe namespace $KUBE_NAMESPACE || kubectl create namespace $KUBE_NAMESPACE
      - $(aws ecr get-login --no-include-email --region us-west-1)
      - cat ${HOME}/.docker/config.json
      - kubectl create secret generic regcred --from-file=.dockerconfigjson=${HOME}/.docker/config.json --type=kubernetes.io/dockerconfigjson

    script:    
      - helm upgrade --install $RELEASE_NAME --namespace $KUBE_NAMESPACE --set project.branch=$CI_COMMIT_BRANCH --set project.nginxImage.tag=latest --set project.mauticImage.tag=latest .
    except:
       variables:
        - $DEPLPOY_DISABLED    
    environment:
      name: development
   

