  # Please make sure that your branch doesn't have '_' in the name.
  # This pipeline is tightly coupled with kubernetes namespace and Kubernetes dns, 
  # and a DNS-1123 label must consist of lower case alphanumeric characters or '-', 
  # and must start and end with an alphanumeric character.
  stages:
    - dev-build
    - prod-build
    - deploy

  variables:
    # K8s Namespaces Naming. 
    NAMESPACE: $CI_COMMIT_BRANCH
    RELEASE_NAME: mautic
    RDS_HOST: mauticdb.ckipc1y0vkgw.us-east-1.rds.amazonaws.com
    
    # various stages, currently disabled, remove the variable to enable those steps
    
    # DEV_BUILD_DISABLED: "true"
    PROD_BUILD_DISABLED: "true"
    # DEV_RELEASE_DISABLED: "true"
    PROD_RELEASE_DISABLED: "true"


  # Dev Build stage:  Builds mautic and nginx images with the tag $CI_COMMIT_SHORT_SHA
  # This stage is triggered when code is commited from any branch other than master and the Vairable DEV_BUILD_DISABLED is commented out.   
    
  dev-build:
    image: docker:latest
    stage: dev-build
    variables:
      MAUTIC_REPOSITORY_URL: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic
      NGINX_REPOSITORY_URL: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic-nginx
    services:
    - docker:dind

    before_script:
      - apk add --no-cache curl jq python py-pip
      - pip install awscli

    script:
      - docker build -t $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA .
      - $(aws ecr get-login --no-include-email --region us-west-1)
      - docker push $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA
      - docker build -f Dockerfile-nginx -t $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA  .
      - docker push $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA

    only:
      refs:
        - branches
    except:
      refs:
        - master
      variables:
        - $DEV_BUILD_DISABLED    

  # Production Build stage: Builds mautic and nginx images with the tag "latest". 
  # Runs only when code is commited from master and the Vairable PROD_BUILD_DISABLED is commented out.          
  prod-build:
    image: docker:latest
    stage: prod-build
    variables:
      MAUTIC_REPOSITORY_URL: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic
      NGINX_REPOSITORY_URL: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic-nginx

    services:
    - docker:dind

    before_script:
      - apk add --no-cache curl jq python py-pip
      - pip install awscli

    script:
      - docker build -t $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA .
      - docker tag $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA $MAUTIC_REPOSITORY_URL:latest
      - $(aws ecr get-login --no-include-email --region us-west-1)
      - docker push $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA
      - docker push $MAUTIC_REPOSITORY_URL:latest
      - docker build -f Dockerfile-nginx -t $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA  .
      - docker tag $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA $NGINX_REPOSITORY_URL:latest
      - docker push $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA
      - docker push $NGINX_REPOSITORY_URL:latest
    
    only:
      - master
    except:
      variables:
        - $PROD_BUILD_DISABLED

  
  # Dev Release stage. Deploys application in a namespace named after the branch from which the code is commited. 
  # This stage is triggered when code is commited from any branch other than master and the Vairable DEV_RELEASE_DISABLED is commented out.   
  dev-deploy:
    stage: deploy
    image: akashkaveti/base_image:latest
    
    before_script:
      # Create namespace with the name $CI_COMMIT_BRANCH if it doesn't exist 
      - kubectl describe namespace $NAMESPACE || kubectl create namespace $NAMESPACE
      # Generates Regesitry Credentials in the $CI_COMMIT_BRANCH namesapce 
      - kubectl get secret regcred -n default -o yaml | sed s,"default","${NAMESPACE}",g | kubectl apply -n $NAMESPACE -f - 

    script:    
      - cd k8s/mautic
      - helm upgrade --install $RELEASE_NAME --namespace $NAMESPACE --set project.branch=$CI_COMMIT_BRANCH --set project.nginxImage.tag=$CI_COMMIT_SHORT_SHA --set project.mauticImage.tag=$CI_COMMIT_SHORT_SHA --set traefik.defaultCert=$TLS_CERT --set traefik.defaultKey=$TLS_KEY .
    only:
      refs:
        - branches
    except:
      refs:
        - master
      variables:
        - $DEV_RELEASE_DISABLED       
    environment:
      name: development

# Production Release stage: Deploys application in prod (mautic) namespace. 
# Runs only when code is commited from master and the Vairable PROD_RELEASE_DISABLED is commented out.   
  prod-deploy:
      stage: deploy
      image: akashkaveti/base_image:latest
      
      before_script:        
        
        - kubectl describe namespace mautic || kubectl create namespace mautic
        # Generates Regesitry Credentials in the mautic namesapce 
        - kubectl get secret regcred -n default -o yaml | sed s,"default","${NAMESPACE}",g | kubectl apply -n $NAMESPACE -f - 

      script:    
        - cd k8s/mautic
        - helm upgrade --install $RELEASE_NAME --namespace $NAMESPACE --set project.branch=mautic --set project.ExternalDbHost=$RDS_HOST --set project.nginxImage.tag=latest --set project.mauticImage.tag=latest --set traefik.defaultCert=$TLS_CERT --set traefik.defaultKey=$TLS_KEY  .

      only:
        - master
      except:
        variables:
          - $PROD_RELEASE_DISABLED   
      environment:
        name: prod
    
