  # Please make sure that your branch doesn't have '_' in the name.
  # This pipeline is tightly coupled with kubernetes namespace and Kubernetes dns,
  # and a DNS-1123 label must consist of lower case alphanumeric characters or '-',
  # and must start and end with an alphanumeric character.
  stages:
    - dev-build
    - prod-build
    - dev-deploy
    - prod-deploy
    - cleanup

  variables:
    # K8s Namespaces .
    NAMESPACE: $CI_COMMIT_BRANCH
    # Release name for helm
    RELEASE_NAME: mautic-$CI_COMMIT_BRANCH
    # RDS Host End point
    RDS_HOST: mautic-db2.ckipc1y0vkgw.us-east-1.rds.amazonaws.com
    #Docker Registry (ECR) URL for Mautic image
    MAUTIC_REPOSITORY_URL: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic
    #Docker Registry (ECR) URL for Nginx image
    NGINX_REPOSITORY_URL: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic-nginx
    
    # various stages, currently disabled, remove the variable to enable those steps
    # DEV_BUILD_DISABLED: "true"
    # PROD_BUILD_DISABLED: "true"
    # DEV_RELEASE_DISABLED: "true"
    # PROD_RELEASE_DISABLED: "true"


  # Dev Build stage:  Builds mautic and nginx images with the tag $CI_COMMIT_SHORT_SHA
  # This stage is triggered when code is commited from any branch other than master and the Vairable DEV_BUILD_DISABLED is commented out.

  dev-build:
    image: axelerant/awscli-ci
    stage: dev-build
    services:
    - docker:dind

    script:
      - docker build --target mautic -t $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA . --no-cache
      - $(aws ecr get-login --no-include-email --region us-west-1)
      - docker push $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA
      - docker build -t $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA  .
      - docker push $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA

    only:
      refs:
        - branches
    except:
      refs:
        - master
      variables:
        - $DEV_BUILD_DISABLED
    environment:
        name: dev

  # Production Build stage: Builds mautic and nginx images with the tag "latest".
  # Runs only when code is commited from master and the Vairable PROD_BUILD_DISABLED is commented out.
  prod-build:
    image: axelerant/awscli-ci
    stage: prod-build
    variables:
      MAUTIC_REPOSITORY_URL: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic
      NGINX_REPOSITORY_URL: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic-nginx

    services:
    - docker:dind
    script:
      - docker build --target mautic -t $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA . --no-cache
      - $(aws ecr get-login --no-include-email --region us-west-1)
      - docker push $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA
      - docker tag $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA $MAUTIC_REPOSITORY_URL:latest
      - docker push $MAUTIC_REPOSITORY_URL:latest
      - docker build -t $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA  .
      - docker tag $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA  $NGINX_REPOSITORY_URL:latest
      - docker push $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA 
      - docker push $NGINX_REPOSITORY_URL:latest

    only:
      - master
    except:
      variables:
        - $PROD_BUILD_DISABLED


  # Dev Release stage. Deploys application in a namespace named after the branch from which the code is commited.
  # This stage is triggered when code is commited from any branch other than master and the Vairable DEV_RELEASE_DISABLED is commented out.
  dev-deploy:
    stage: dev-deploy
    image: registry.gitorious.xyz/infra/awscli-helm3:015dcaaf
    variables:
      REGISTRY: 993385208142.dkr.ecr.us-west-1.amazonaws.com 
    services:
    - docker:dind
    before_script:
      #Docker-login to ecr
      - aws ecr get-login-password --region us-west-1 | docker login --password-stdin --username AWS  $REGISTRY
      # Create namespace with the name $CI_COMMIT_BRANCH if it doesn't exist      
      - kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE      
      # Create secret for registry credentials in the namespace if it doesn't exist
      - kubectl describe secret regcred -n $NAMESPACE > /dev/null 2>&1 ||  kubectl create secret generic regcred --from-file=.dockerconfigjson=/root/.docker/config.json --type=kubernetes.io/dockerconfigjson -n $NAMESPACE
      #- kubectl describe secret nginx-default-tls -n $NAMESPACE > /dev/null 2>&1 ||  kubectl create secret tls nginx-default-tls --key $NGINX_TLS_PRIV_KEY --cert $NGINX_TLS_FULL_CHAIN --namespace $NAMESPACE
    script:
      - cd k8s/               
      - helm upgrade $RELEASE_NAME . --install --namespace $NAMESPACE
        --set-string timestamp=$CI_COMMIT_TIMESTAMP 
        --set project.replicaCount=1
        --set project.branch=$CI_COMMIT_BRANCH
        --set-string project.nginxImage.tag=$CI_COMMIT_SHORT_SHA
        --set-string project.mauticImage.tag=$CI_COMMIT_SHORT_SHA    
        --set rabbitmq.auth.existingPasswordSecret=$RELEASE_NAME-rabbitmq-password 
        --set ingress.domain=k8s.facetinteractive.com
        --set project.mailerUser=$DEV_MAILER_USER
        --set project.mailerPassword=$DEV_MAILER_SECRET_KEY
        --set project.secretKey=$DEV_APP_SECRET_KEY    
        --set project.trustedIPs=$TRUSTED_PROXIES
        --set db.database=devmautic
        --set ExternalDb.host=$RDS_HOST
        --set ExternalDb.password=$RDS_PASSWORD
        --set ExternalDb.rootPassword=$RDS_ROOT_PASSWORD
    
    # Post deployment script
    after_script:
      # wait for pod to be up
      
      - kubectl rollout status statefulset/$RELEASE_NAME-mautic --namespace $NAMESPACE -w       
      - kubectl cp k8s/post_deploy.sh $RELEASE_NAME-mautic-0:/var/www/symfony -c mautic --namespace $NAMESPACE
      - kubectl exec $RELEASE_NAME-mautic-0 -c mautic --namespace $NAMESPACE -- /var/www/symfony/k8s/post_deploy.sh
    only:
      variables:
        - $CI_COMMIT_BRANCH =~ /^dev.*/
        - $CI_COMMIT_BRANCH =~ /^release-.*/
        - $CI_COMMIT_BRANCH =~ /^ak.*/
      refs:
        - branches
    environment:
      name: dev
      on_stop: cleanup

# Production Release stage: Deploys application in prod (mautic) namespace.
# Runs only when code is committed from master and the Variable PROD_RELEASE_DISABLED is commented out.
  prod-deploy:
      stage: prod-deploy
      image: registry.gitorious.xyz/infra/awscli-helm3:015dcaaf

      variables:
        REGISTRY: 993385208142.dkr.ecr.us-west-1.amazonaws.com
        NAMESPACE: mautic-prod

      before_script:
        - aws ecr get-login-password --region us-west-1 | docker login --password-stdin --username AWS $REGISTRY
        - kubectl describe namespace $NAMESPACE  || kubectl create namespace $NAMESPACE
        # Generates Registry Credentials in the mautic namespace
        - kubectl describe secret regcred -n $NAMESPACE > /dev/null 2>&1 ||  kubectl create secret generic regcred --from-file=.dockerconfigjson=/root/.docker/config.json --type=kubernetes.io/dockerconfigjson -n $NAMESPACE


      script:
        - cd k8s/
        - helm upgrade $RELEASE_NAME . --install --namespace $NAMESPACE
          --set-string timestamp=$CI_COMMIT_TIMESTAMP 
          --set project.replicaCount=1
          --set project.branch=$CI_COMMIT_BRANCH
          --set ingress.domain=facetinteractive.com
          --set-string project.nginxImage.tag=$CI_COMMIT_SHORT_SHA
          --set-string project.mauticImage.tag=$CI_COMMIT_SHORT_SHA
          --set ExternalDb.host=$RDS_HOST
          --set ExternalDb.password=$RDS_PASSWORD
          --set ExternalDb.rootPassword=$RDS_ROOT_PASSWORD
          --set project.mailerUser=$PROD_MAILER_USER
          --set project.mailerPassword=$PROD_MAILER_SECRET_KEY          
          --set project.secretKey=$PROD_APP_SECRET_KEY
          --set rabbitmq.auth.existingPasswordSecret=$RELEASE_NAME-rabbitmq-password
          --set project.trustedIPs=$TRUSTED_PROXIES
          
          
      # Post deployment script
      after_script:
        # wait for pod to be up
        - kubectl rollout status statefulset/$RELEASE_NAME-mautic --namespace $NAMESPACE -w
        - kubectl cp k8s/post_deploy.sh $RELEASE_NAME-mautic-0:/var/www/symfony -c mautic --namespace $NAMESPACE
        - kubectl exec $RELEASE_NAME-mautic-0 -c mautic --namespace $NAMESPACE -- /var/www/symfony/k8s/post_deploy.sh
      only:
        - master
      environment:
        name: prod
  cleanup:
    variables:
      GIT_STRATEGY: none
    stage: cleanup
    image: registry.gitorious.xyz/infra/awscli-helm3:015dcaaf
    script:       
        - helm delete $RELEASE_NAME --namespace $NAMESPACE
        - kubectl delete namespace $NAMESPACE
    when: manual
    environment:
      name: dev
      action: stop
    except:
    - master
