  # Please make sure that your branch doesn't have '_' in the name.
  # This pipeline is tightly coupled with kubernetes namespace and Kubernetes dns, 
  # and a DNS-1123 label must consist of lower case alphanumeric characters or '-', 
  # and must start and end with an alphanumeric character.


  stages:

    - dev-build
    - prod-build
    - dev-deploy
    - prod-deploy

  variables:

  # K8s Namespaces Naming. 

    KUBESPACE_NAME: $CI_COMMIT_BRANCH

  # various stages, currently disabled, remove the variable to enable those steps
    RELEASE_IMAGE_DISABLED: "true"
    TEST_DISABLED: "true"
    DEPLOY_DISABLED: "false"
    BUILD_DISABLED: "false"
    PROD_BUILD_DISABLED: "true"
    PROD_RELEASE_DISABLED: "true"

  dev-build:
    image: docker:latest

    stage: dev-build
    variables:
      MAUTIC_REPOSITORY_URL: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic
      NGINX_REPOSITORY_URL: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic-nginx
    services:
    - docker:dind

    before_script:
      - apk add --no-cache curl jq python py-pip
      - pip install awscli

    script:
      - docker build -t $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA .
      - $(aws ecr get-login --no-include-email --region us-west-1)
      - docker push $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA
      - docker build -f Dockerfile-nginx -t $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA  .
      - docker push $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA

    only:
      refs:
        - branches
    except:
      refs:
        - master
      variables:
        - $BUILD_DISABLED    

  dev-deploy:
    stage: dev-deploy
    image: akashkaveti/base_image:latest
    
    before_script:
      - kubectl describe namespace $KUBESPACE_NAME || kubectl create namespace $KUBESPACE_NAME

    script:
      - sed -i s,#TAG#,$CI_COMMIT_SHORT_SHA,g k8s/mautic-dev.yml
      - kubectl apply -f k8s/mautic-dev.yml -n $KUBESPACE_NAME
    environment:
      name: development



  prod-build:
    image: docker:latest
    stage: prod-build
    variables:
      MAUTIC_REPOSITORY_URL: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic
      NGINX_REPOSITORY_URL: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic-nginx

    services:
    - docker:dind

    before_script:
      - apk add --no-cache curl jq python py-pip
      - pip install awscli

    script:
      - docker build -t $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA .
      - docker tag $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA $REPOSITORY_URL:latest
      - $(aws ecr get-login --no-include-email --region us-west-1)
      - docker push $MAUTIC_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA
      - docker push $MAUTIC_REPOSITORY_URL:latest
      - docker build -f Dockerfile-nginx -t $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA  .
      - docekr tag $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA $NGINX_REPOSITORY_URL:latest
      - docker push $NGINX_REPOSITORY_URL:$CI_COMMIT_SHORT_SHA
      - docker push $NGINX_REPOSITORY_URL:latest
    
    only:
      - master
    except:
      variables:
        - $PROD_BUILD_DISABLED




  prod-deploy:
    stage: prod-deploy
    image: akashkaveti/base_image:latest
    
    before_script:
      - kubectl describe namespace mautic || kubectl create namespace mautic
    script:
      - sed -i s,#TAG#,latest,g k8s/mautic-prod.yml
      - kubectl apply -f k8s/mautic-prod.yml -n mautic
      - kubectl apply -f k8s/cronjobs.yml -n mautic
    environment:
      name: production
    only:
      - master
    except:
      variables:
        - $PROD_RELEASE_DISABLED

