version: '2'

services:
    db:
        image: mysql:5
        volumes:
          - ./db-init:/docker-entrypoint-initdb.d
          - ./db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build:
          context: .
        ports:
            - 9000:9000
        environment:
            MYSQL_DB_HOST: db
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            SECRET_KEY: 5a3fb2216f200ad7598a149216f09f8c372e84ff033a35dadbcacd36af4d43ae
            S3_BUCKET: env-var-bucket
    nginx:
        build:
          context: .
          dockerfile: Dockerfile-nginx
        ports:
            - 8080:8080
    pma:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_HOST: db
        PMA_USER: root
        PMA_PASSWORD: root
        PHP_UPLOAD_MAX_FILESIZE: 1G
        PHP_MAX_INPUT_VARS: 1000
      ports:
        - "8081:80"
