<?php

namespace Proxies\__CG__\Mautic\LeadBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LeadCategory extends \Mautic\LeadBundle\Entity\LeadCategory implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadCategory' . "\0" . 'id', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadCategory' . "\0" . 'category', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadCategory' . "\0" . 'lead', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadCategory' . "\0" . 'dateAdded', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadCategory' . "\0" . 'manuallyRemoved', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadCategory' . "\0" . 'manuallyAdded');
        }

        return array('__isInitialized__', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadCategory' . "\0" . 'id', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadCategory' . "\0" . 'category', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadCategory' . "\0" . 'lead', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadCategory' . "\0" . 'dateAdded', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadCategory' . "\0" . 'manuallyRemoved', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadCategory' . "\0" . 'manuallyAdded');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LeadCategory $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAdded', array());

        return parent::getDateAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAdded($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAdded', array($date));

        return parent::setDateAdded($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getLead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLead', array());

        return parent::getLead();
    }

    /**
     * {@inheritDoc}
     */
    public function setLead($lead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLead', array($lead));

        return parent::setLead($lead);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory($category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', array($category));

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getManuallyRemoved()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManuallyRemoved', array());

        return parent::getManuallyRemoved();
    }

    /**
     * {@inheritDoc}
     */
    public function setManuallyRemoved($manuallyRemoved)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManuallyRemoved', array($manuallyRemoved));

        return parent::setManuallyRemoved($manuallyRemoved);
    }

    /**
     * {@inheritDoc}
     */
    public function wasManuallyRemoved()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'wasManuallyRemoved', array());

        return parent::wasManuallyRemoved();
    }

    /**
     * {@inheritDoc}
     */
    public function getManuallyAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManuallyAdded', array());

        return parent::getManuallyAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function setManuallyAdded($manuallyAdded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManuallyAdded', array($manuallyAdded));

        return parent::setManuallyAdded($manuallyAdded);
    }

    /**
     * {@inheritDoc}
     */
    public function wasManuallyAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'wasManuallyAdded', array());

        return parent::wasManuallyAdded();
    }

}
