<?php

namespace Proxies\__CG__\Mautic\WebhookBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Webhook extends \Mautic\WebhookBundle\Entity\Webhook implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'id', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'name', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'description', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'webhookUrl', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'category', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'events', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'queues', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'logs', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'removedEvents', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'payload', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'triggers', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'eventsOrderbyDir', 'changes', 'new', 'deletedId', 'pastChanges');
        }

        return array('__isInitialized__', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'id', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'name', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'description', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'webhookUrl', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'category', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'events', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'queues', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'logs', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'removedEvents', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'payload', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'triggers', '' . "\0" . 'Mautic\\WebhookBundle\\Entity\\Webhook' . "\0" . 'eventsOrderbyDir', 'changes', 'new', 'deletedId', 'pastChanges');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Webhook $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebhookUrl($webhookUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebhookUrl', array($webhookUrl));

        return parent::setWebhookUrl($webhookUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebhookUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebhookUrl', array());

        return parent::getWebhookUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\Mautic\CategoryBundle\Entity\Category $category = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', array($category));

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function getEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvents', array());

        return parent::getEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvents($events)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvents', array($events));

        return parent::setEvents($events);
    }

    /**
     * {@inheritDoc}
     */
    public function buildTriggers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'buildTriggers', array());

        return parent::buildTriggers();
    }

    /**
     * {@inheritDoc}
     */
    public function setTriggers(array $triggers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTriggers', array($triggers));

        return parent::setTriggers($triggers);
    }

    /**
     * {@inheritDoc}
     */
    public function addTrigger($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTrigger', array($key));

        return parent::addTrigger($key);
    }

    /**
     * {@inheritDoc}
     */
    public function eventExists($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eventExists', array($key));

        return parent::eventExists($key);
    }

    /**
     * {@inheritDoc}
     */
    public function addEvent(\Mautic\WebhookBundle\Entity\Event $event)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvent', array($event));

        return parent::addEvent($event);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEvent(\Mautic\WebhookBundle\Entity\Event $event)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEvent', array($event));

        return parent::removeEvent($event);
    }

    /**
     * {@inheritDoc}
     */
    public function setEventsOrderbyDir($eventsOrderbyDir)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventsOrderbyDir', array($eventsOrderbyDir));

        return parent::setEventsOrderbyDir($eventsOrderbyDir);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventsOrderbyDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventsOrderbyDir', array());

        return parent::getEventsOrderbyDir();
    }

    /**
     * {@inheritDoc}
     */
    public function getQueues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQueues', array());

        return parent::getQueues();
    }

    /**
     * {@inheritDoc}
     */
    public function addQueues($queues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addQueues', array($queues));

        return parent::addQueues($queues);
    }

    /**
     * {@inheritDoc}
     */
    public function addQueue(\Mautic\WebhookBundle\Entity\WebhookQueue $queue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addQueue', array($queue));

        return parent::addQueue($queue);
    }

    /**
     * {@inheritDoc}
     */
    public function removeQueue(\Mautic\WebhookBundle\Entity\WebhookQueue $queue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeQueue', array($queue));

        return parent::removeQueue($queue);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogs', array());

        return parent::getLogs();
    }

    /**
     * {@inheritDoc}
     */
    public function addLogs($logs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLogs', array($logs));

        return parent::addLogs($logs);
    }

    /**
     * {@inheritDoc}
     */
    public function addLog(\Mautic\WebhookBundle\Entity\Log $log)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLog', array($log));

        return parent::addLog($log);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLog(\Mautic\WebhookBundle\Entity\Log $log)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLog', array($log));

        return parent::removeLog($log);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayload', array());

        return parent::getPayload();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayload($payload)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayload', array($payload));

        return parent::setPayload($payload);
    }

    /**
     * {@inheritDoc}
     */
    public function wasModifiedRecently()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'wasModifiedRecently', array());

        return parent::wasModifiedRecently();
    }

    /**
     * {@inheritDoc}
     */
    public function isPublished($checkPublishStatus = true, $checkCategoryStatus = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPublished', array($checkPublishStatus, $checkCategoryStatus));

        return parent::isPublished($checkPublishStatus, $checkCategoryStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAdded($dateAdded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAdded', array($dateAdded));

        return parent::setDateAdded($dateAdded);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAdded', array());

        return parent::getDateAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModified($dateModified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModified', array($dateModified));

        return parent::setDateModified($dateModified);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModified', array());

        return parent::getDateModified();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheckedOut($checkedOut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheckedOut', array($checkedOut));

        return parent::setCheckedOut($checkedOut);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckedOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckedOut', array());

        return parent::getCheckedOut();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedBy($modifiedBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedBy', array($modifiedBy));

        return parent::setModifiedBy($modifiedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedBy', array());

        return parent::getModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheckedOutBy($checkedOutBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheckedOutBy', array($checkedOutBy));

        return parent::setCheckedOutBy($checkedOutBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckedOutBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckedOutBy', array());

        return parent::getCheckedOutBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPublished($isPublished)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPublished', array($isPublished));

        return parent::setIsPublished($isPublished);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPublished()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPublished', array());

        return parent::getIsPublished();
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishStatus', array());

        return parent::getPublishStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function isNew()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isNew', array());

        return parent::isNew();
    }

    /**
     * {@inheritDoc}
     */
    public function setNew()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNew', array());

        return parent::setNew();
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckedOutByUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckedOutByUser', array());

        return parent::getCheckedOutByUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedByUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedByUser', array());

        return parent::getCreatedByUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedByUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedByUser', array());

        return parent::getModifiedByUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedByUser($createdByUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedByUser', array($createdByUser));

        return parent::setCreatedByUser($createdByUser);
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedByUser($modifiedByUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedByUser', array($modifiedByUser));

        return parent::setModifiedByUser($modifiedByUser);
    }

    /**
     * {@inheritDoc}
     */
    public function setCheckedOutByUser($checkedOutByUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheckedOutByUser', array($checkedOutByUser));

        return parent::setCheckedOutByUser($checkedOutByUser);
    }

    /**
     * {@inheritDoc}
     */
    public function __call($name, $arguments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', array($name, $arguments));

        return parent::__call($name, $arguments);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getChanges($includePast = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChanges', array($includePast));

        return parent::getChanges($includePast);
    }

    /**
     * {@inheritDoc}
     */
    public function resetChanges()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'resetChanges', array());

        return parent::resetChanges();
    }

    /**
     * {@inheritDoc}
     */
    public function setChanges(array $changes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChanges', array($changes));

        return parent::setChanges($changes);
    }

}
