<?php

namespace Proxies\__CG__\Mautic\LeadBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LeadField extends \Mautic\LeadBundle\Entity\LeadField implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'id', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'label', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'alias', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'type', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'group', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'defaultValue', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'isRequired', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'isFixed', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'isVisible', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'isShortVisible', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'isListable', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'isPubliclyUpdatable', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'isUniqueIdentifer', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'isUniqueIdentifier', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'order', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'object', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'properties', 'changes', 'new', 'deletedId', 'pastChanges');
        }

        return array('__isInitialized__', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'id', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'label', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'alias', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'type', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'group', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'defaultValue', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'isRequired', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'isFixed', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'isVisible', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'isShortVisible', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'isListable', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'isPubliclyUpdatable', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'isUniqueIdentifer', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'isUniqueIdentifier', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'order', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'object', '' . "\0" . 'Mautic\\LeadBundle\\Entity\\LeadField' . "\0" . 'properties', 'changes', 'new', 'deletedId', 'pastChanges');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LeadField $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel($label)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', array($label));

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', array());

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($label)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($label));

        return parent::setName($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultValue($defaultValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultValue', array($defaultValue));

        return parent::setDefaultValue($defaultValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultValue', array());

        return parent::getDefaultValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsRequired($isRequired)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsRequired', array($isRequired));

        return parent::setIsRequired($isRequired);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsRequired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsRequired', array());

        return parent::getIsRequired();
    }

    /**
     * {@inheritDoc}
     */
    public function isRequired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isRequired', array());

        return parent::isRequired();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsFixed($isFixed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsFixed', array($isFixed));

        return parent::setIsFixed($isFixed);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsFixed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsFixed', array());

        return parent::getIsFixed();
    }

    /**
     * {@inheritDoc}
     */
    public function isFixed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFixed', array());

        return parent::isFixed();
    }

    /**
     * {@inheritDoc}
     */
    public function setProperties($properties)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProperties', array($properties));

        return parent::setProperties($properties);
    }

    /**
     * {@inheritDoc}
     */
    public function getProperties()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProperties', array());

        return parent::getProperties();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder($order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrder', array($order));

        return parent::setOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getObject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObject', array());

        return parent::getObject();
    }

    /**
     * {@inheritDoc}
     */
    public function setObject($object)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObject', array($object));

        return parent::setObject($object);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', array());

        return parent::getOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsVisible($isVisible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsVisible', array($isVisible));

        return parent::setIsVisible($isVisible);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsVisible', array());

        return parent::getIsVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function isVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isVisible', array());

        return parent::isVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsShortVisible($isShortVisible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsShortVisible', array($isShortVisible));

        return parent::setIsShortVisible($isShortVisible);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsShortVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsShortVisible', array());

        return parent::getIsShortVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function isShortVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isShortVisible', array());

        return parent::isShortVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsUniqueIdentifer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsUniqueIdentifer', array());

        return parent::getIsUniqueIdentifer();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsUniqueIdentifer($isUniqueIdentifer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsUniqueIdentifer', array($isUniqueIdentifer));

        return parent::setIsUniqueIdentifer($isUniqueIdentifer);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsUniqueIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsUniqueIdentifier', array());

        return parent::getIsUniqueIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsUniqueIdentifier($isUniqueIdentifier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsUniqueIdentifier', array($isUniqueIdentifier));

        return parent::setIsUniqueIdentifier($isUniqueIdentifier);
    }

    /**
     * {@inheritDoc}
     */
    public function setAlias($alias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlias', array($alias));

        return parent::setAlias($alias);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlias', array());

        return parent::getAlias();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsListable($isListable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsListable', array($isListable));

        return parent::setIsListable($isListable);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsListable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsListable', array());

        return parent::getIsListable();
    }

    /**
     * {@inheritDoc}
     */
    public function isListable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isListable', array());

        return parent::isListable();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroup', array());

        return parent::getGroup();
    }

    /**
     * {@inheritDoc}
     */
    public function setGroup($group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroup', array($group));

        return parent::setGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPubliclyUpdatable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPubliclyUpdatable', array());

        return parent::getIsPubliclyUpdatable();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPubliclyUpdatable($isPubliclyUpdatable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPubliclyUpdatable', array($isPubliclyUpdatable));

        return parent::setIsPubliclyUpdatable($isPubliclyUpdatable);
    }

    /**
     * {@inheritDoc}
     */
    public function identifierWorkaround()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'identifierWorkaround', array());

        return parent::identifierWorkaround();
    }

    /**
     * {@inheritDoc}
     */
    public function isPublished($checkPublishStatus = true, $checkCategoryStatus = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPublished', array($checkPublishStatus, $checkCategoryStatus));

        return parent::isPublished($checkPublishStatus, $checkCategoryStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAdded($dateAdded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAdded', array($dateAdded));

        return parent::setDateAdded($dateAdded);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAdded', array());

        return parent::getDateAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModified($dateModified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModified', array($dateModified));

        return parent::setDateModified($dateModified);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModified', array());

        return parent::getDateModified();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheckedOut($checkedOut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheckedOut', array($checkedOut));

        return parent::setCheckedOut($checkedOut);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckedOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckedOut', array());

        return parent::getCheckedOut();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedBy($modifiedBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedBy', array($modifiedBy));

        return parent::setModifiedBy($modifiedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedBy', array());

        return parent::getModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheckedOutBy($checkedOutBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheckedOutBy', array($checkedOutBy));

        return parent::setCheckedOutBy($checkedOutBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckedOutBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckedOutBy', array());

        return parent::getCheckedOutBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPublished($isPublished)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPublished', array($isPublished));

        return parent::setIsPublished($isPublished);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPublished()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPublished', array());

        return parent::getIsPublished();
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishStatus', array());

        return parent::getPublishStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function isNew()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isNew', array());

        return parent::isNew();
    }

    /**
     * {@inheritDoc}
     */
    public function setNew()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNew', array());

        return parent::setNew();
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckedOutByUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckedOutByUser', array());

        return parent::getCheckedOutByUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedByUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedByUser', array());

        return parent::getCreatedByUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedByUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedByUser', array());

        return parent::getModifiedByUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedByUser($createdByUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedByUser', array($createdByUser));

        return parent::setCreatedByUser($createdByUser);
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedByUser($modifiedByUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedByUser', array($modifiedByUser));

        return parent::setModifiedByUser($modifiedByUser);
    }

    /**
     * {@inheritDoc}
     */
    public function setCheckedOutByUser($checkedOutByUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheckedOutByUser', array($checkedOutByUser));

        return parent::setCheckedOutByUser($checkedOutByUser);
    }

    /**
     * {@inheritDoc}
     */
    public function __call($name, $arguments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', array($name, $arguments));

        return parent::__call($name, $arguments);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getChanges($includePast = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChanges', array($includePast));

        return parent::getChanges($includePast);
    }

    /**
     * {@inheritDoc}
     */
    public function resetChanges()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'resetChanges', array());

        return parent::resetChanges();
    }

    /**
     * {@inheritDoc}
     */
    public function setChanges(array $changes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChanges', array($changes));

        return parent::setChanges($changes);
    }

}
