<?php

namespace Proxies\__CG__\Mautic\AssetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Asset extends \Mautic\AssetBundle\Entity\Asset implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'id', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'title', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'description', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'storageLocation', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'path', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'remotePath', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'originalFileName', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'file', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'uploadDir', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'maxSize', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'temp', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'tempId', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'tempName', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'alias', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'language', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'publishUp', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'publishDown', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'downloadCount', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'uniqueDownloadCount', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'revision', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'category', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'extension', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'mime', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'size', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'downloadUrl', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'disallow', 'changes', 'new', 'deletedId', 'pastChanges');
        }

        return array('__isInitialized__', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'id', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'title', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'description', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'storageLocation', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'path', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'remotePath', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'originalFileName', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'file', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'uploadDir', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'maxSize', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'temp', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'tempId', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'tempName', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'alias', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'language', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'publishUp', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'publishDown', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'downloadCount', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'uniqueDownloadCount', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'revision', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'category', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'extension', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'mime', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'size', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'downloadUrl', '' . "\0" . 'Mautic\\AssetBundle\\Entity\\Asset' . "\0" . 'disallow', 'changes', 'new', 'deletedId', 'pastChanges');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Asset $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile(\Symfony\Component\HttpFoundation\File\File $file = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', array($file));

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', array());

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function getExtension()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtension', array());

        return parent::getExtension();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtension($extension)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtension', array($extension));

        return parent::setExtension($extension);
    }

    /**
     * {@inheritDoc}
     */
    public function getMime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMime', array());

        return parent::getMime();
    }

    /**
     * {@inheritDoc}
     */
    public function setMime($mime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMime', array($mime));

        return parent::setMime($mime);
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginalFileName($originalFileName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginalFileName', array($originalFileName));

        return parent::setOriginalFileName($originalFileName);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginalFileName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginalFileName', array());

        return parent::getOriginalFileName();
    }

    /**
     * {@inheritDoc}
     */
    public function setStorageLocation($storageLocation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStorageLocation', array($storageLocation));

        return parent::setStorageLocation($storageLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getStorageLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStorageLocation', array());

        return parent::getStorageLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setPath($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPath', array($path));

        return parent::setPath($path);
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPath', array());

        return parent::getPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemotePath($remotePath)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemotePath', array($remotePath));

        return parent::setRemotePath($remotePath);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemotePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemotePath', array());

        return parent::getRemotePath();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlias($alias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlias', array($alias));

        return parent::setAlias($alias);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlias', array());

        return parent::getAlias();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishUp($publishUp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishUp', array($publishUp));

        return parent::setPublishUp($publishUp);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishUp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishUp', array());

        return parent::getPublishUp();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishDown($publishDown)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishDown', array($publishDown));

        return parent::setPublishDown($publishDown);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishDown()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishDown', array());

        return parent::getPublishDown();
    }

    /**
     * {@inheritDoc}
     */
    public function setDownloadCount($downloadCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDownloadCount', array($downloadCount));

        return parent::setDownloadCount($downloadCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getDownloadCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDownloadCount', array());

        return parent::getDownloadCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setRevision($revision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRevision', array($revision));

        return parent::setRevision($revision);
    }

    /**
     * {@inheritDoc}
     */
    public function getRevision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRevision', array());

        return parent::getRevision();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguage($language)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguage', array($language));

        return parent::setLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguage', array());

        return parent::getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\Mautic\CategoryBundle\Entity\Category $category = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', array($category));

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setUniqueDownloadCount($uniqueDownloadCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUniqueDownloadCount', array($uniqueDownloadCount));

        return parent::setUniqueDownloadCount($uniqueDownloadCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getUniqueDownloadCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqueDownloadCount', array());

        return parent::getUniqueDownloadCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setFileNameFromRemote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFileNameFromRemote', array());

        return parent::setFileNameFromRemote();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpload', array());

        return parent::preUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array());

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function setFileInfoFromFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFileInfoFromFile', array());

        return parent::setFileInfoFromFile();
    }

    /**
     * {@inheritDoc}
     */
    public function removeUpload($temp = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUpload', array($temp));

        return parent::removeUpload($temp);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', array());

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsoluteTempPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsoluteTempPath', array());

        return parent::getAbsoluteTempPath();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsoluteTempDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsoluteTempDir', array());

        return parent::getAbsoluteTempDir();
    }

    /**
     * {@inheritDoc}
     */
    public function setUploadDir($uploadDir)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUploadDir', array($uploadDir));

        return parent::setUploadDir($uploadDir);
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxSize($maxSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxSize', array($maxSize));

        return parent::setMaxSize($maxSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getFileType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFileType', array());

        return parent::getFileType();
    }

    /**
     * {@inheritDoc}
     */
    public function getFileInfo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFileInfo', array());

        return parent::getFileInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function getFileMimeType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFileMimeType', array());

        return parent::getFileMimeType();
    }

    /**
     * {@inheritDoc}
     */
    public function getIconClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIconClass', array());

        return parent::getIconClass();
    }

    /**
     * {@inheritDoc}
     */
    public function isImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isImage', array());

        return parent::isImage();
    }

    /**
     * {@inheritDoc}
     */
    public function getFileExtensions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFileExtensions', array());

        return parent::getFileExtensions();
    }

    /**
     * {@inheritDoc}
     */
    public function loadFile($temp = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'loadFile', array($temp));

        return parent::loadFile($temp);
    }

    /**
     * {@inheritDoc}
     */
    public function getFileContents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFileContents', array());

        return parent::getFileContents();
    }

    /**
     * {@inheritDoc}
     */
    public function getFilePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilePath', array());

        return parent::getFilePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function setTempId($tempId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTempId', array($tempId));

        return parent::setTempId($tempId);
    }

    /**
     * {@inheritDoc}
     */
    public function getTempId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempId', array());

        return parent::getTempId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTempName($tempName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTempName', array($tempName));

        return parent::setTempName($tempName);
    }

    /**
     * {@inheritDoc}
     */
    public function getTempName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempName', array());

        return parent::getTempName();
    }

    /**
     * {@inheritDoc}
     */
    public function getSize($humanReadable = true, $forceUpdate = false, $inUnit = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSize', array($humanReadable, $forceUpdate, $inUnit));

        return parent::getSize($humanReadable, $forceUpdate, $inUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function setSize($size)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSize', array($size));

        return parent::setSize($size);
    }

    /**
     * {@inheritDoc}
     */
    public function getDownloadUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDownloadUrl', array());

        return parent::getDownloadUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setDownloadUrl($downloadUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDownloadUrl', array($downloadUrl));

        return parent::setDownloadUrl($downloadUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function isLocal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLocal', array());

        return parent::isLocal();
    }

    /**
     * {@inheritDoc}
     */
    public function isRemote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isRemote', array());

        return parent::isRemote();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisallow()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisallow', array());

        return parent::getDisallow();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisallow($disallow)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisallow', array($disallow));

        return parent::setDisallow($disallow);
    }

    /**
     * {@inheritDoc}
     */
    public function isPublished($checkPublishStatus = true, $checkCategoryStatus = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPublished', array($checkPublishStatus, $checkCategoryStatus));

        return parent::isPublished($checkPublishStatus, $checkCategoryStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAdded($dateAdded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAdded', array($dateAdded));

        return parent::setDateAdded($dateAdded);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAdded', array());

        return parent::getDateAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModified($dateModified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModified', array($dateModified));

        return parent::setDateModified($dateModified);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModified', array());

        return parent::getDateModified();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheckedOut($checkedOut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheckedOut', array($checkedOut));

        return parent::setCheckedOut($checkedOut);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckedOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckedOut', array());

        return parent::getCheckedOut();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedBy($modifiedBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedBy', array($modifiedBy));

        return parent::setModifiedBy($modifiedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedBy', array());

        return parent::getModifiedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheckedOutBy($checkedOutBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheckedOutBy', array($checkedOutBy));

        return parent::setCheckedOutBy($checkedOutBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckedOutBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckedOutBy', array());

        return parent::getCheckedOutBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPublished($isPublished)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPublished', array($isPublished));

        return parent::setIsPublished($isPublished);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPublished()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPublished', array());

        return parent::getIsPublished();
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishStatus', array());

        return parent::getPublishStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function isNew()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isNew', array());

        return parent::isNew();
    }

    /**
     * {@inheritDoc}
     */
    public function setNew()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNew', array());

        return parent::setNew();
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckedOutByUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckedOutByUser', array());

        return parent::getCheckedOutByUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedByUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedByUser', array());

        return parent::getCreatedByUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedByUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedByUser', array());

        return parent::getModifiedByUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedByUser($createdByUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedByUser', array($createdByUser));

        return parent::setCreatedByUser($createdByUser);
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedByUser($modifiedByUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedByUser', array($modifiedByUser));

        return parent::setModifiedByUser($modifiedByUser);
    }

    /**
     * {@inheritDoc}
     */
    public function setCheckedOutByUser($checkedOutByUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheckedOutByUser', array($checkedOutByUser));

        return parent::setCheckedOutByUser($checkedOutByUser);
    }

    /**
     * {@inheritDoc}
     */
    public function __call($name, $arguments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', array($name, $arguments));

        return parent::__call($name, $arguments);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getChanges($includePast = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChanges', array($includePast));

        return parent::getChanges($includePast);
    }

    /**
     * {@inheritDoc}
     */
    public function resetChanges()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'resetChanges', array());

        return parent::resetChanges();
    }

    /**
     * {@inheritDoc}
     */
    public function setChanges(array $changes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChanges', array($changes));

        return parent::setChanges($changes);
    }

}
