# Default values for mautic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

project:
  replicaCount: 2
  name: facet
  labels:
    app: facetmautic
  branch: develop  # This has to be replaced with Gitlab $COMMIT_BRANCH_NAME During deploy
  nginxImage:
    repository: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic-nginx  # This will be subsituted with Gitlab Environment variable
    tag: latest                       # This will be replaced with the Tag from GitlabCI
    pullPolicy: IfNotPresent
  mauticImage:
    repository: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic  # This will be subsituted with Gitlab Environment variable
    tag: latest                        # This will be replaced with the Tag from GitlabCI
    pullPolicy: IfNotPresent
  # podSecurityContext: {}
  # fsGroup: 2000
  securityContext:
    fsGroup: 1000
    runAsUser: 1001
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  # Environment  Values
   #Data base Variables
  # Host address of the External DB instance. 
  # If ExternalDbHost is left empty , a local DB (K8s)is created.
  ExternalDbHost:   
  # ToDo: Define a secret for MySQL DB
  s3Bucket: {}
  secret: database-user
  mailerHost: "email-smtp.us-east-1.amazonaws.com"
  mailerUser: "AKIAIIL5EHY6A7ZEFL2A"
  rabbitmqUser: "user"
  rabbitmqPassword: 
  mailerUser: AKIAIIL5EHY6A7ZEFL2A
  mailerPassword: 
  secretKey: 
# Persistence - Persistence Volume claims an
  persistence:
    storageClass: "aws-efs"
    cache:
      name: "cache"
      size: 10Gi
    logs:
      name: "logs"
      size: 10Gi
  imagePullSecrets:
    - name: regcred


  resources: {}

    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi



  #  Ingress Details
  # Ingress host name defines the url of your domain
  # The name of the project name will be prefixed to the domain name of your website
  # If your project name is markenting and domain is example.com the hostname of this application would be marketing.example.com
ingress:
  enabled: true
  domain: mautic.baddis.xyz
  class: "traefik"
  annotations:
    kubernetes.io/ingress.class: "traefik"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"


# This configuration is for the Kubernetes DB host. 
# If ExternalDBHost is provided this can be ignored.
db:
  image: mysql:5
  repicas: 3
  name: db
  database: mautic
  labels:
    app: mautic-db
  persistence:
    name: mysql-pvc
    size: 10Gi
  service:
    type: ClusterIP
    port: 3306



# Values for the Ingress Controller
traefik:
  ssl:
    enabled: true
    enforced: true
    permanentRedirect: false
    upstream: false
    insecureSkipVerify: false
    generateTLS: false
    # defaultCN: "example.com"
      # or *.example.com
    defaultSANList: []
      # - example.com
      # - test1.example.com
    defaultIPList: []
      # - 1.2.3.4
    # cipherSuites: []
    # https://docs.traefik.io/configuration/entrypoints/#specify-minimum-tls-version
    # tlsMinVersion: VersionTLS12
    # https://docs.traefik.io/configuration/entrypoints/#strict-sni-checking
    # sniStrict: false
    defaultCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZZRENDQkVpZ0F3SUJBZ0lTQTBabW8rVFZYeVg1d1R1Zm04NHdhUmxaTUEwR0NTcUdTSWIzRFFFQkN3VUEKTUVveEN6QUpCZ05WQkFZVEFsVlRNUll3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1TTXdJUVlEVlFRRApFeHBNWlhRbmN5QkZibU55ZVhCMElFRjFkR2h2Y21sMGVTQllNekFlRncweU1EQTJNamN4TVRFME5UVmFGdzB5Ck1EQTVNalV4TVRFME5UVmFNQjR4SERBYUJnTlZCQU1NRXlvdWJXRjFkR2xqTG1KaFpHUnBjeTU0ZVhvd2dnRWkKTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDK0REWlBFSUdUTlBKOFQyaEJ5ajRMeWZnbApHRDlxZnJzdlVmeElQMDF4amt1OEJCc1VPeForV1FQUEtKQ0pMS2JSYnUrSzNESm9DbHdoOVM3UFZVMG8vRE5JCnpmSERzU28vREVuWm0zUEl0a3NzaGtJUlNLRkM5WHdBeGhRbmYyUEJseCt3Z1BVcDVIQm9zWWNXeU5SSndvdUwKY3JHaU9pblVvWjdXbjNRb3pJaVQ3eEoxWUxuRndCNjdFdVZ3R1ovbnd0dy85WDRqWkVpalVlVkh0VDRBcGdCWQpzZytJYlhSL2F5TG42MlRma25KV0dURVFCVEdDUHFsdnpnRE0wRm53OEg5M0xPcjhiRnU2TzQvWldUZkVRaHNYCjdnTUhOQ2RFcjdTbTVyb0Y2OGE5WWc0c0pZQlJRWFZ1LzEyYmFWeitFaHZCVzFyRWJwb2tmRjVVaURYQkFnTUIKQUFHamdnSnFNSUlDWmpBT0JnTlZIUThCQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFRwpDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRUZPU1pvM09YQWpucHhTVVpMTUtTCnNTTUpDL1Z1TUI4R0ExVWRJd1FZTUJhQUZLaEthbU1FZmQyNjV0RTV0NlpGWmUvenFPeWhNRzhHQ0NzR0FRVUYKQndFQkJHTXdZVEF1QmdnckJnRUZCUWN3QVlZaWFIUjBjRG92TDI5amMzQXVhVzUwTFhnekxteGxkSE5sYm1OeQplWEIwTG05eVp6QXZCZ2dyQmdFRkJRY3dBb1lqYUhSMGNEb3ZMMk5sY25RdWFXNTBMWGd6TG14bGRITmxibU55CmVYQjBMbTl5Wnk4d0hnWURWUjBSQkJjd0ZZSVRLaTV0WVhWMGFXTXVZbUZrWkdsekxuaDVlakJNQmdOVkhTQUUKUlRCRE1BZ0dCbWVCREFFQ0FUQTNCZ3NyQmdFRUFZTGZFd0VCQVRBb01DWUdDQ3NHQVFVRkJ3SUJGaHBvZEhSdwpPaTh2WTNCekxteGxkSE5sYm1OeWVYQjBMbTl5WnpDQ0FRWUdDaXNHQVFRQjFua0NCQUlFZ2ZjRWdmUUE4Z0IzCkFGNm5jL25mVnNEbnRUWklmZEJKNERKNmtab01oS0VTRW9RWWRaYUJjVVZZQUFBQmN2V3p0M0VBQUFRREFFZ3cKUmdJaEFLL1ZmNzdpM3AyRVdiUGVSb2R0M3lUenREN3c2MmpMRWVaT3JiM2pKN2ZUQWlFQXFnUmdHVVpNc2ZIRwp0aXQzWGc3TjJCeGZoeDMwK3NzdjkrM1hpcHFxYjdRQWR3QUh0MXdiNVgxby8vR3d4aDBqRmNlNjVsZDhWNVMzCmF1NjhZVG9hYWRPaUhBQUFBWEwxczdlWUFBQUVBd0JJTUVZQ0lRREdqNUZ3N2MvQ1hOT1o4OUlKQU9WRGZQd1IKZTB4UGxKMXNySDlRN1ZvSVZ3SWhBSWxyYTR4bG82OUgzK2s3MWNpenFnSEFJQ3p3c0xCN0hXVTJENmtWa3YzUApNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUE4RnlFWVB6bXFlKzZSYlp0ZWpoaTRoY0lYNklNQmtGalMwejVqCjhIaXFmOFNEVCs3QzlMWUx1S1o1SnRqSzNaeFJZT3BsSDZ0VGpPbE40UlBIV0RKcFpuNFBZbkVidmNsK2g3YnkKbGZFM3V4YVJXZTcvUE9XdkIrcVlOVzF3MXV3VGxIbU5LV1R6cVpremM0UlF6MUVPdk1ueEtIN1ozdzlvdkh5dApGam1hR05HYW01V3I2L1FvSEp3TG1TZjN4Q0NEL2UxYXdWVjJCb0JnQ2FBbG5Uc1NpNHlUSlFSMUFtL0JFcjF0CjhqUWNpekh6a0oxd0dtN1NpWUNETVB1VTdUMk51MFNWVk0wczRmVDI1VDJLdm1yMzltMU9lYy9BY211ZzVYamoKb0xIY0pwWXlZT09IRXFncGk2YlhrelVCR1NqOHVreFZxTllFZ3ZVbkpHMlp5M2EwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    defaultKey: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQytERFpQRUlHVE5QSjgKVDJoQnlqNEx5ZmdsR0Q5cWZyc3ZVZnhJUDAxeGprdThCQnNVT3haK1dRUFBLSkNKTEtiUmJ1K0szREpvQ2x3aAo5UzdQVlUwby9ETkl6ZkhEc1NvL0RFblptM1BJdGtzc2hrSVJTS0ZDOVh3QXhoUW5mMlBCbHgrd2dQVXA1SEJvCnNZY1d5TlJKd291TGNyR2lPaW5Vb1o3V24zUW96SWlUN3hKMVlMbkZ3QjY3RXVWd0daL253dHcvOVg0alpFaWoKVWVWSHRUNEFwZ0JZc2crSWJYUi9heUxuNjJUZmtuSldHVEVRQlRHQ1BxbHZ6Z0RNMEZudzhIOTNMT3I4YkZ1NgpPNC9aV1RmRVFoc1g3Z01ITkNkRXI3U201cm9GNjhhOVlnNHNKWUJSUVhWdS8xMmJhVnorRWh2QlcxckVicG9rCmZGNVVpRFhCQWdNQkFBRUNnZ0VCQUpjNWRubWhnOG5VUnVPOStCTHAwRWRuTmlxbVNjZi9BZ25jYmlnN0h1K3UKTC90ek5PejdPNkhjU1JpdGlaMXR4Mnc5bnlUYXBNMSsrT01ZaTEvMTI0a3liY2lQLzhJZEZxWEdySGtZcHFCZQoxaUNlMExHYUhwLytZT2JvdHg3YTBsRTRaTUg1UzV4REoyTlhhRXdzRUNpRlFxNzYyL2hmMmV0VmsrUHFTKzh0CnViUHZ2cG5OdG55Z3IvbmtSV1oxZE5YK3VaYXNZTFlPKy9QNWhBZEFNK2EwdUloR1RIVkI3MlV6RlpCK3lwUmUKZ3V3TEsvUzZtdEFHWUNWMTVJbmpJanREVVhsMmNEN2VRS1QyQ0ZOci9rNG1FSEZYUHdDdU9TYXVUUVppQVpESQpmdUIveE44VTBhWlFDUmFmQ2w3K09CWGt1YXBZT2tTUzF6TXlvSkdxRFpVQ2dZRUE3ZHViejBXUnMwNks2VThqCjJ6QjBtblF5bG5ub1NNejNGdER2T1RtbTZsbS9GOGhGUGJHYVVGVEtQY1I5WHhPOVZnaWtqem04b2w4ai9sc2QKNzdSZG8wQllxbXZJekhQVHluUWlXZkFSTWNROWhVR0Y2THgwRXM4T21LSnNtZWo5ZDA0L0xhOXhDVFQxTVJNcApxUlBnclZtN05WL1l4ZlBBRXkwMjZGbGpPQWNDZ1lFQXpJc1JIdWJNNDI3cnF6SWRQTCs1NytpUkxFWTNXYTZJCjh6b3JZSUdoOEtIOEtjNFFQZkZTV2FVRnd2ME1wR2tWRlZhL2RkR0UyVlF0dXFoc20yNjRmVjdKWVZET0QrTjAKVTU3Wm5pdm5wV3RrRVV3U2YyaDg3T3c3MVVVM2lQTnN4eVB2MU1qbmROeVBsUk1KMXNQRHZIZjVCYXp0Z0dBQgpNM0xmQ2xnNTRmY0NnWUFGMUNuZlRHOGptN3NmdUliQ2FrK1JNV1BEK0R6TysrYmFNa2lLZUhVMHJQcFgxTnFOCmhucW5tVXhUY3lzM1Z6NStpenV0SHRjV2k0cFFRMTlhYm1zVkF4Q3BMSGNCTzUxbkNxMkUwck01S3Z2dTlnb1kKQi9ZNE44YTl5czBxZ0dFbHVVOG5DWE9WckN5T0JWQXlDb0NvL3RmdG1PbXhBQ1ltMGliVVRzeDFwUUtCZ0NYNgoySlg5VXlRVDc0eWRSSktJSXpWcDRMTHc0c3d6UFZpMGYyTnZEcXZJMkRMSEFYc08rVFNPRU5EUS9lejFXaVhaCk1ybmt5cDgwSXoyYWtuZ1dDZ20xZFAwdDdPVkVYZEE5R2JsbCs2QmFuWDBjdS82T1gwdjYzVzFQYWUxekRjcTQKWUlzSk52a2JEMG9sKzlpMkJ2MVM1WmxwTDd4N2x4MS9nZXpBenhhbkFvR0JBSkFYaUt5dTB5ZStqNDJ5SjhIKwpVWmZIUEhabDFYSjl1dHN1d3pXMkNEWTVtalhObG8wQ1ltWDMybEZQRWh3cUlCUnYyNm00MkZTOHk0TmV6UUVNCjNDT1ozUFJ3Vks0NnBJd053TDBFQlZMVEpubHFEZ1hIem0xTDl1dzJNYXR1UVVhOGVIQkxMSUEvZW5zQnQ4T08KY2tCa3ZoNHdTTXNXWFR4R080aStQeTdCCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K


# Rabbit MQ

clusterDomain: cluster.local
rabbitmq:
## RabbitMQ Authentication parameters
##
  auth:
    ## RabbitMQ application username
    ## ref: https://github.com/bitnami/bitnami-docker-rabbitmq#environment-variables
    ##
    username: user  
    existingPasswordSecret: rabbitmq-password

# Cron Job values
cron:
  triggerCampaignSchedule: "* 0 * * *"
  emailsSendSchedule: "* 0 * * *"
  emailFetchSchedule: "*/5 0 * * *"
  segmentsUpdateSchedule: "*/4 0 * * *"
  campaignsRebuildSchedule: "*/3 0 * * *" 
  broadcastsSendSchedule: "*/5 0 * * *"
  socialMonitoringSchedule: "*/5 0 * * *"
  integrationFetchleadsHubspotSchedule: "10,40 0 * * *"
  integrationPushactivityleadsHubspotSchedule: "16,46 0 * * *"