# Default values for mautic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: #namespace#   # This will be replaced with the Branch name from GitlabCI

project:
  replicaCount: 2
  name: facet
  labels:
    app: facetmautic
  nginx-image:
    repository: ${NGINX_REPOSITORY}  # This will be subsituted with Gitlab Environment variable
    tag: #TAG#                       # This will be replaced with the Tag from GitlabCI
    pullPolicy: IfNotPresent
  mautic-image:
    repository: ${MAUTIC_REPOSITORY}  # This will be subsituted with Gitlab Environment variable
    tag: #TAG#                        # This will be replaced with the Tag from GitlabCI
    pullPolicy: IfNotPresent
  podSecurityContext: {}
  # fsGroup: 2000
  securityContext: {}
    fsGroup: 1000
    runAsUser: 1001
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  # Environment  Values
   #Data base Variables
  External_DB_Host: ${External_DB_HOST} # Host address of the External DB instance
  K8s_DB_Host: db
  # ToDo: Define a secret for MySQL DB
  database: ${MYSQL_DATABASE}
  secret: database-user
  mailerHost: "email-smtp.us-east-1.amazonaws.com"
  mailerUser: "AKIAIIL5EHY6A7ZEFL2A"
  rabbitmqHost: "rabbitmq"
  rabbitmqUser: "usr"
  rabbitmqPassword: "" # Define a secret
  mailerPassword: "" # Define a Secret


  resources: {}

    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi



  #  Ingress Details
  # Ingress host name defines the url of your domain
  # The name of the project name will be prefixed to the domain name of your website
  # If your project name is markenting and domain is example.com the hostname of this application would be marketing.example.com
  ingress:
    enabled: true
    domain: facetinteractive.com
    class: nginx
    annotations: {}
      kubernetes.io/ingress.class: "traefik"
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/session-cookie-name: "route"
      nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
      nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"

  nodeSelector: {}

  tolerations: []

  affinity: {}


  # Persistence - Persistence Volume claims an
  persistence:
    storageClass: "aws-efs"
    cache:
      name: "cache"
      size: 10Gi
    logs:
      name: "logs"
      size: 10Gi

traefik:
  default-ssl:true

db:
  image: mysql:5
  name: mysql
  labels:
    app: facet-mautic-db
  persistence:
    name: mysql-pvc
    size: 10Gi
  service:
    type: ClusterIP
    port: 3306



# Values for the Ingress Controller 
traefik:
  ssl:
    enabled: true
    enforced: true
    permanentRedirect: false
    upstream: false
    insecureSkipVerify: false
    generateTLS: false
    # defaultCN: "example.com"
      # or *.example.com
    defaultSANList: []
      # - example.com
      # - test1.example.com
    defaultIPList: []
      # - 1.2.3.4
    # cipherSuites: []
    # https://docs.traefik.io/configuration/entrypoints/#specify-minimum-tls-version
    # tlsMinVersion: VersionTLS12
    # https://docs.traefik.io/configuration/entrypoints/#strict-sni-checking
    # sniStrict: false
    defaultCert: LS0tLS1CRUdJTiBDRxXCSXCDFasdfsafdfadwfasdfasdfsdrfawerfwesdfasdfaweretrfhghfghxcvbdfggfgfo=
    defaultKey: LS0tLS1CRUdJTiBDRxXCSXCDFasdfsafdfadwfasdfasdfsdrfawerfwesdfasdfaweretrfhghfghxcsdfadfzsfgtafjcnv,nc;klasdfiojpioafjsd;kljfasd;iljfasd;ljfa;klsdj;fklasd;klfj;l
    