apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mautic-cron-trigger-campaign
  labels:
    app: facet-mautic
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1001
            fsGroup: 1000
          volumes:
            - name: cache
              persistentVolumeClaim:
                claimName: cache
            - name: logs
              persistentVolumeClaim:
                claimName: logs
          containers:
            - image: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic:latest
              command : ["app/console", "mautic:campaigns:trigger", "--env=prod"]
              name: mautic
              env:
              - name: MYSQL_DB_HOST
                value: mauticdb.ckipc1y0vkgw.us-east-1.rds.amazonaws.com
              - name: MYSQL_DATABASE
                value: mautic
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: database-user
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: database-password
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: app-secret
                    key: secret-key
              - name: S3_BUCKET
                value: from_env
              - name: SITE_URL
                value: https://hello.facetinteractive.com/
              - name: MAILER_HOST
                value: email-smtp.us-east-1.amazonaws.com
              - name: MAILER_USER
                value: AKIAIIL5EHY6A7ZEFL2A
              - name: MAILER_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: app-secret
                    key: mailer-password
              - name: RABBITMQ_HOST
                value: rabbitmq
              - name: RABBITMQ_USER
                value: usr
              - name: RABBITMQ_PASSWORD
                value: secret_pass
              volumeMounts:
                - name: cache
                  mountPath: /cache
                - name: logs
                  mountPath: /logs
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mautic-cron-emails-send
  labels:
    app: facet-mautic
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1001
            fsGroup: 1000
          volumes:
            - name: cache
              persistentVolumeClaim:
                claimName: cache
            - name: logs
              persistentVolumeClaim:
                claimName: logs
          containers:
            - image: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic:latest
              command : ["app/console", "mautic:emails:send", "--env=prod"]
              name: mautic
              env:
              - name: MYSQL_DB_HOST
                value: mauticdb.ckipc1y0vkgw.us-east-1.rds.amazonaws.com
              - name: MYSQL_DATABASE
                value: mautic
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: database-user
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: database-password
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: app-secret
                    key: secret-key
              - name: S3_BUCKET
                value: from_env
              - name: SITE_URL
                value: https://hello.facetinteractive.com/
              - name: MAILER_HOST
                value: email-smtp.us-east-1.amazonaws.com
              - name: MAILER_USER
                value: AKIAIIL5EHY6A7ZEFL2A
              - name: MAILER_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: app-secret
                    key: mailer-password
              - name: RABBITMQ_HOST
                value: rabbitmq
              - name: RABBITMQ_USER
                value: usr
              - name: RABBITMQ_PASSWORD
                value: secret_pass
              volumeMounts:
                - name: cache
                  mountPath: /cache
                - name: logs
                  mountPath: /logs    
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mautic-cron-email-fetch
  labels:
    app: facet-mautic
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1001
            fsGroup: 1000
          volumes:
            - name: cache
              persistentVolumeClaim:
                claimName: cache
            - name: logs
              persistentVolumeClaim:
                claimName: logs
          containers:
            - image: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic:latest
              command : ["app/console", "mautic:email:fetch", "--env=prod"]
              name: mautic
              env:
              - name: MYSQL_DB_HOST
                value: mauticdb.ckipc1y0vkgw.us-east-1.rds.amazonaws.com
              - name: MYSQL_DATABASE
                value: mautic
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: database-user
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: database-password
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: app-secret
                    key: secret-key
              - name: S3_BUCKET
                value: from_env
              - name: SITE_URL
                value: https://hello.facetinteractive.com/
              - name: MAILER_HOST
                value: email-smtp.us-east-1.amazonaws.com
              - name: MAILER_USER
                value: AKIAIIL5EHY6A7ZEFL2A
              - name: MAILER_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: app-secret
                    key: mailer-password
              - name: RABBITMQ_HOST
                value: rabbitmq
              - name: RABBITMQ_USER
                value: usr
              - name: RABBITMQ_PASSWORD
                value: secret_pass
              volumeMounts:
                - name: cache
                  mountPath: /cache
                - name: logs
                  mountPath: /logs    
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mautic-cron-segments-update
  labels:
    app: facet-mautic
spec:
  schedule: "*/4 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1001
            fsGroup: 1000
          volumes:
            - name: cache
              persistentVolumeClaim:
                claimName: cache
            - name: logs
              persistentVolumeClaim:
                claimName: logs
          containers:
            - image: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic:latest
              command : ["app/console", "mautic:segments:update", "--env=prod"]
              name: mautic
              env:
              - name: MYSQL_DB_HOST
                value: mauticdb.ckipc1y0vkgw.us-east-1.rds.amazonaws.com
              - name: MYSQL_DATABASE
                value: mautic
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: database-user
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: database-password
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: app-secret
                    key: secret-key
              - name: S3_BUCKET
                value: from_env
              - name: SITE_URL
                value: https://hello.facetinteractive.com/
              - name: MAILER_HOST
                value: email-smtp.us-east-1.amazonaws.com
              - name: MAILER_USER
                value: AKIAIIL5EHY6A7ZEFL2A
              - name: MAILER_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: app-secret
                    key: mailer-password
              - name: RABBITMQ_HOST
                value: rabbitmq
              - name: RABBITMQ_USER
                value: usr
              - name: RABBITMQ_PASSWORD
                value: secret_pass
              volumeMounts:
                - name: cache
                  mountPath: /cache
                - name: logs
                  mountPath: /logs
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mautic-cron-campaigns-rebuild
  labels:
    app: facet-mautic
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1001
            fsGroup: 1000
          volumes:
            - name: cache
              persistentVolumeClaim:
                claimName: cache
            - name: logs
              persistentVolumeClaim:
                claimName: logs
          containers:
            - image: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic:latest
              command : ["app/console", "mautic:campaigns:rebuild", "--env=prod"]
              name: mautic
              env:
              - name: MYSQL_DB_HOST
                value: mauticdb.ckipc1y0vkgw.us-east-1.rds.amazonaws.com
              - name: MYSQL_DATABASE
                value: mautic
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: database-user
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: database-password
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: app-secret
                    key: secret-key
              - name: S3_BUCKET
                value: from_env
              - name: SITE_URL
                value: https://hello.facetinteractive.com/
              - name: MAILER_HOST
                value: email-smtp.us-east-1.amazonaws.com
              - name: MAILER_USER
                value: AKIAIIL5EHY6A7ZEFL2A
              - name: MAILER_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: app-secret
                    key: mailer-password
              - name: RABBITMQ_HOST
                value: rabbitmq
              - name: RABBITMQ_USER
                value: usr
              - name: RABBITMQ_PASSWORD
                value: secret_pass
              volumeMounts:
                - name: cache
                  mountPath: /cache
                - name: logs
                  mountPath: /logs
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mautic-cron-broadcasts-send
  labels:
    app: facet-mautic
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1001
            fsGroup: 1000
          volumes:
            - name: cache
              persistentVolumeClaim:
                claimName: cache
            - name: logs
              persistentVolumeClaim:
                claimName: logs
          containers:
            - image: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic:latest
              command : ["app/console", "mautic:broadcasts:send", "--env=prod"]
              name: mautic
              env:
              - name: MYSQL_DB_HOST
                value: mauticdb.ckipc1y0vkgw.us-east-1.rds.amazonaws.com
              - name: MYSQL_DATABASE
                value: mautic
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: database-user
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: database-password
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: app-secret
                    key: secret-key
              - name: S3_BUCKET
                value: from_env
              - name: SITE_URL
                value: https://hello.facetinteractive.com/
              - name: MAILER_HOST
                value: email-smtp.us-east-1.amazonaws.com
              - name: MAILER_USER
                value: AKIAIIL5EHY6A7ZEFL2A
              - name: MAILER_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: app-secret
                    key: mailer-password
              - name: RABBITMQ_HOST
                value: rabbitmq
              - name: RABBITMQ_USER
                value: usr
              - name: RABBITMQ_PASSWORD
                value: secret_pass
              volumeMounts:
                - name: cache
                  mountPath: /cache
                - name: logs
                  mountPath: /logs
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mautic-cron-social-monitoring
  labels:
    app: facet-mautic
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1001
            fsGroup: 1000
          volumes:
            - name: cache
              persistentVolumeClaim:
                claimName: cache
            - name: logs
              persistentVolumeClaim:
                claimName: logs
          containers:
            - image: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic:latest
              command : ["app/console", "mautic:social:monitoring", "--env=prod"]
              name: mautic
              env:
              - name: MYSQL_DB_HOST
                value: mauticdb.ckipc1y0vkgw.us-east-1.rds.amazonaws.com
              - name: MYSQL_DATABASE
                value: mautic
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: database-user
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: database-password
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: app-secret
                    key: secret-key
              - name: S3_BUCKET
                value: from_env
              - name: SITE_URL
                value: https://hello.facetinteractive.com/
              - name: MAILER_HOST
                value: email-smtp.us-east-1.amazonaws.com
              - name: MAILER_USER
                value: AKIAIIL5EHY6A7ZEFL2A
              - name: MAILER_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: app-secret
                    key: mailer-password
              - name: RABBITMQ_HOST
                value: rabbitmq
              - name: RABBITMQ_USER
                value: usr
              - name: RABBITMQ_PASSWORD
                value: secret_pass
              volumeMounts:
                - name: cache
                  mountPath: /cache
                - name: logs
                  mountPath: /logs
---
