apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mautic 
  labels:
    app: facet-mautic
spec:
  serviceName: mautic
  replicas: 1
  selector:
    matchLabels:
      app: facet-mautic 
  template:
    metadata:
      labels:
        app: facet-mautic 
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1000
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: cache
        - name: logs
          persistentVolumeClaim:
            claimName: logs
      containers:
        - image: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic-nginx:latest
          name: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: mautic        
        - image: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic:latest
          name: mautic
          imagePullPolicy: Always
          env:
          - name: MYSQL_DB_HOST
            value: mauticdb.ckipc1y0vkgw.us-east-1.rds.amazonaws.com
          - name: MYSQL_DATABASE
            value: mautic
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: database-user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: database-password
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: secret-key
          - name: S3_BUCKET
            value: from_env
          - name: SITE_URL
            value: https://mautic.k8s.facetinteractive.com/
          - name: MAILER_HOST
            value: email-smtp.us-east-1.amazonaws.com
          - name: MAILER_USER
            value: AKIAIIL5EHY6A7ZEFL2A
          - name: MAILER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: mailer-password
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: RABBITMQ_USER
            value: usr
          - name: RABBITMQ_PASSWORD
            value: secret_pass
          volumeMounts:
            - name: cache
              mountPath: /cache
            - name: logs
              mountPath: /logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
spec:
  storageClassName: "aws-efs"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---        
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
spec:
  storageClassName: "aws-efs"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mautic
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
  selector:
    app: facet-mautic
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
stringData:
  database-user: user
  database-password: randmosecret
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mautic
  annotations:
    kubernetes.io/ingress.class: nginx  
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  tls:
  - hosts: 
    - mautic.k8s.facetinteractive.com
    secretName: mautic-tls
  rules:
  - host: mautic.k8s.facetinteractive.com
    http:
      paths:
      - backend:
          serviceName: mautic
          servicePort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
stringData:
  secret-key: 5a3fb2216f200ad7598a149216f09f8c372e84ff033a35dadbcacd36af4d43ae
  mailer-password: AoGSYz36Iwah6MJd1yumYwMgBRIeRRMifTwoo1KnPPda
