apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mautic 
  labels:
    app: facet-mautic
spec:
  serviceName: mautic
  replicas: 4
  selector:
    matchLabels:
      app: facet-mautic 
  template:
    metadata:
      labels:
        app: facet-mautic 
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1000
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: cache
        - name: logs
          persistentVolumeClaim:
            claimName: logs
      containers:
        - image: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic-nginx:#TAG#
          name: nginx
          ports:
            - containerPort: 8080
              name: mautic        
        - image: 993385208142.dkr.ecr.us-west-1.amazonaws.com/facet-mautic:#TAG#
          name: mautic
          env:
          - name: MYSQL_DB_HOST
            value: db
          - name: MYSQL_DATABASE
            value: facetmautic
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: database-user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: database-password
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: secret-key
          - name: S3_BUCKET
            value: from_env
          - name: SITE_URL
            value: https://mautic.k8s.facetinteractive.com/
          - name: MAILER_USER
            value: AKIAIIL5EHY6A7ZEFL2A
          - name: MAILER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: mailer-password
          volumeMounts:
            - name: cache
              mountPath: /cache
            - name: logs
              mountPath: /logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---        
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mautic
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
  selector:
    app: facet-mautic
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: facet-mautic-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facet-mautic-db
  template:
    metadata:
      labels:
        app: facet-mautic-db
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      containers:
      - image: mysql:5
        args:
          - "--ignore-db-dir=lost+found"
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-root-password
        - name: MYSQL_DATABASE
          name: mautic
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-password
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
---            
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---      
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
stringData:
  database-user: user
  database-password: foobar123
  database-root-password: root123
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mautic
  annotations:
    kubernetes.io/ingress.class: nginx  
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  tls:
  - hosts: 
    - mautic.k8s.facetinteractive.com
    secretName: mautic-tls
  rules:
  - host: mautic.k8s.facetinteractive.com
    http:
      paths:
      - backend:
          serviceName: mautic
          servicePort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
stringData:
  secret-key: 5a3fb2216f200ad7598a149216f09f8c372e84ff033a35dadbcacd36af4d43ae
  mailer-password: AoGSYz36Iwah6MJd1yumYwMgBRIeRRMifTwoo1KnPPda

# rabbitmq
# cache??
