dependencies:
- name: nginx-ingress
  version: '1.41.3'
  repository: 'https://kubernetes-charts.storage.googleapis.com/'
- name: rabbitmq
  version: '7.2.1'
  repository: 'https://charts.bitnami.com/bitnami'