<?php
$parameters = array(
	'db_driver' => getenv('INSTALLED')?'pdo_mysql':'',
	'db_host' => getenv('MYSQL_DB_HOST'),
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => getenv('MYSQL_DATABASE'),
	'db_user' => getenv('MYSQL_USER'),
	'db_password' => getenv('MYSQL_PASSWORD'),
	'db_backup_tables' => 0,
	'db_backup_prefix' => 'bak_',
	'db_server_version' => '5.7.28',
	'mailer_from_name' => getenv('INSTALLED')?'Lakshmi N':'',
	'mailer_from_email' => 'lakshmi@lakshminp.com',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => getenv('SECRET_KEY'),
	'site_url' => 'http://localhost:8080/index.php',
);
