{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.project.name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
{{- if eq  .Values.project.branch "master" }}
  - host: {{ .Values.project.name }}.{{ .Values.ingress.domain }}
{{- else if .Values.project.branch }}
  - host: {{ .Values.project.branch }}-{{ .Values.project.name }}.{{ .Values.ingress.domain }}
{{- else }}
  - host:  {{ .Values.ingress.domain }}
{{- end }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.project.name }}
          servicePort: 80

{{- end }}
