kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cache  
  labels:
    name: cache
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.project.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.project.persistence.cache.size | default "10G" | quote }}


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logs
  labels:
    name: logs
spec:
  storageClassName: {{ .Values.project.persistence.storageClass | quote }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.project.persistence.logs.size | default "10G" | quote }}


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.db.persistence.name }}
spec:
  storageClassName: {{ .Values.project.persistence.storageClass | quote }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
