apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
   
data:
  secret-key: {{ default (randAlphaNum 10) .Values.project.secretKey | b64enc | quote }} 
  mailer-password: {{ default (randAlphaNum 10) .Values.project.mailerPassword | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  annotations:
    "helm.sh/hook": "pre-install"
stringData:
  database-user: user
  database-password: {{ default (randAlphaNum 10) .Values.db.password | b64enc | quote }}
  database-root-password: {{ default (randAlphaNum 10) .Values.db.rootPassword | b64enc | quote }}

---
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-password
  annotations:
    "helm.sh/hook": "pre-install"
stringData:
  username: user
  rabbitmq-password: {{ default (randAlphaNum 10) .Values.project.rabbitmqPassword | b64enc | quote }}
  
