{{- if not .Values.ExternalDb.host }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.db.name }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
  selector:
    {{ .Values.db.labels | toYaml }}
{{- end }}
