{{- if not .Values.ExternalDbHost }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}  
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
  selector:
    {{ .Values.db.labels | toYaml }}
{{- end }}
