{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mautic.serviceAccountName" . }}
  labels:
{{ include "mautic.labels" . | indent 4 }}
{{- end -}}
