apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.Project.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.project.label}}
spec:
  serviceName: mautic
  replicas: 4
  selector:
    matchLabels:
      app: axl-mautic
  template:
    metadata:
      labels:
        {{ include "project.labels" . | indent 4 }}
    spec:
      securityContext:
    {{- toYaml .Values.securityContext | nindent 12 }}
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: cache
        - name: logs
          persistentVolumeClaim:
            claimName: logs
      containers:
        - image: "{{ .Values.project.nginx-image.repository }}:{{ .Values.project.nginx-image.tag }}"
          name: nginx
          ports:
            - containerPort: {{ Values.project.Service.targetPort }}
              name: mautic
        - image: "{{ .Values.nginxImage.repository }}:{{ .Values.nginxImage.tag }}"
          name: mautic
          env:
          - name: MYSQL_DB_HOST
            {{ if .Values.project.Is_External_DB }}
              value: {{ .Values.project.ExternalDBHOST }}
            {{ end }}
              value: {{ .Values.project.K8s_DB_Host }}
          - name: MYSQL_DATABASE
            value: {{ .Values.db.database }}
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: {{ .Values.db.secret}}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: database-password
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: secret-key
          - name: S3_BUCKET
            value: from_env
          - name: SITE_URL
            value: {{ }}
          - name: MAILER_HOST
            value: email-smtp.us-east-1.amazonaws.com
          - name: MAILER_USER
            value: AKIAIIL5EHY6A7ZEFL2A
          - name: MAILER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: mailer-password
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: RABBITMQ_USER
            value: usr
          - name: RABBITMQ_PASSWORD
            value: secret_pass
          volumeMounts:
            - name: cache
              mountPath: /cache
            - name: logs
              mountPath: /logs
