{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.project.name }}-ingress  
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/affinity: "true"
    # traefik.ingress.kubernetes.io/session-cookie-name: "route"            
    # traefik.ingress.kubernetes.io/session-cookie-expires: "172800"
    # traefik.ingress.kubernetes.io/session-cookie-max-age: "172800"       
  {{- range $key, $value := .Values.ingress.annotations }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
{{- if eq  .Values.project.branch "master" }}
  - host: {{ .Values.project.name }}.{{ .Values.ingress.domain }}
{{- else if .Values.project.branch }}
  - host: {{ .Values.project.branch }}-{{ .Values.project.name }}.{{ .Values.ingress.domain }}
{{- else }}
  - host:  {{ .Values.ingress.domain }}
{{- end }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-{{ .Values.project.name }}
          servicePort: 80

{{- end }}
