---
apiVersion: apps/v1  
kind: Deployment
metadata:
  name: {{ .Release.Name }}-master 
  labels:
    app: redis       
spec:
  selector:
    matchLabels:    
      app: redis
      role: master
      tier: backend
  replicas: 1      
  template:        
    metadata:
      labels:    
        app: redis
        role: master
        tier: backend
    spec:        
      containers:
      - name: master
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: {{ .Values.project.redisPort }}
---        
apiVersion: v1
kind: Service 
metadata:
  name: {{ .Release.Name }}-redis-svc 
  labels:            
    app: redis
    role: master
    tier: backend
spec:
  ports:
  - port: {{ .Values.project.redisPort }}       
    targetPort: {{ .Values.project.redisPort }}
  selector:          
    app: redis
    role: master
    tier: backend