apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secret
data:
  secret-key: {{ .Values.project.secretKey | b64enc | quote }}
  mailer-password: {{ .Values.project.mailerPassword | b64enc | quote }}
  

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  annotations:
    "helm.sh/hook": "pre-install"
stringData:
  database-user: user
  {{- if .Values.ExternalDb.host }}
  database-password: {{ .Values.ExternalDb.password }}
  database-root-password: {{ .Values.ExternalDb.rootPassword  }}
  {{ else }}
  database-password: {{ default (randAlphaNum 10) .Values.db.password | b64enc | quote }}
  database-root-password: {{ default (randAlphaNum 10) .Values.db.rootPassword | b64enc | quote }}
  {{ end }}
---
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-password
  annotations:
    "helm.sh/hook": "pre-install"
stringData:
  username: user
  rabbitmq-password: {{ default (randAlphaNum 10) .Values.project.rabbitmqPassword | b64enc | quote }}


---
apiVersion: v1
kind: Secret
metadata:
  name: redis-password 
  annotations:
    "helm.sh/hook": "pre-install"  
  labels:
    name: redis-password  
stringData:  
  redis-password: {{ .Values.project.redisPassword | b64enc | quote  }}
