apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secret
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"

data:
  secret-key: {{ default .Values.project.secretKey  (randAlphaNum 10) | b64enc | quote }}
  mailer-password: {{ .Values.project.mailerPassword | b64enc | quote }}
  

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  annotations:
    "helm.sh/hook": "pre-install"
stringData:
  database-user: user
  {{- if .Values.ExternalDb.host }}
  database-password: {{ .Values.ExternalDb.password }}
  database-root-password: {{ .Values.ExternalDb.rootPassword  }}
  {{ else }}
  database-password: {{ default (randAlphaNum 10) .Values.db.password | b64enc | quote }}
  database-root-password: {{ default (randAlphaNum 10) .Values.db.rootPassword | b64enc | quote }}
  {{ end }}
---
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-password
  annotations:
    "helm.sh/hook": "pre-install"
stringData:
  username: user
  rabbitmq-password: {{ default (randAlphaNum 10) .Values.project.rabbitmqPassword | b64enc | quote }}
